### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by DavidBuchanan314** [DavidBuchanan314/pyswargol#1]
- [x] Fix exit cleanup process
- [x] Make Ctrl+C do something sensible...
- [x] create config object to get passed around
- [x] Add CLI options
- [x] Fullscreen mode
- [x] Support non-evenly-divisible heights
- [ ] Optimise frameskip (only serialise whole frame when needed)
- [ ] Option to load custom patterns
- [x] Naive computation option (for perf comparison purposes)
- [ ] Numpy/scipy computation option (likewise) - genuinely curious whether it's faster
